services:
  supla-cloud:
    container_name: ${COMPOSE_PROJECT_NAME}-cloud
    restart: unless-stopped
    image: supla/supla-cloud:${SUPLA_CLOUD_VERSION:-latest}
    env_file:
      - .env
    environment:
      MQTT_BROKER_PROTOCOL: mqtts
      MQTT_BROKER_PORT: 8883
      MQTT_BROKER_TLS: true
    volumes:
      - ./ssl/cloud:/etc/apache2/ssl
      - ${VOLUME_DATA}/cloud-local:/var/www/cloud/var/local
      - ${VOLUME_DATA}/cloud-logs:/var/www/cloud/var/logs
      - supla-server-socket:/supla-server
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - supla-db

  supla-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    image: ${DB_IMAGE}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: supla
      MYSQL_USER: supla
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${VOLUME_DATA}/mysql:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: 50m

  supla-server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    restart: unless-stopped
    image: supla/supla-server:${SUPLA_SERVER_VERSION:-latest}
    env_file:
      - .env
    environment:
      MQTT_BROKER_PROTOCOL: mqtts
      MQTT_BROKER_PORT: 8883
      MQTT_BROKER_TLS: true
    volumes:
      - ./ssl/server:/etc/supla-server/ssl
      - supla-server-socket:/var/run/supla
    ports:
      - "2015:2015"
      - "2016:2016"
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - supla-cloud
      - mosquitto

  mosquitto:
    container_name: ${COMPOSE_PROJECT_NAME}-mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        if [ ! -s /mosquitto/config/passwd ]; then
          mosquitto_passwd -b -c /mosquitto/config/passwd "$$MQTT_BROKER_USERNAME" "$$MQTT_BROKER_PASSWORD";
        fi
        exec mosquitto -c /mosquitto/config/mosquitto.conf
    ports:
      - "${MQTT_TLS_PORT}:8883"
    volumes:
      - ./config/mosquitto/mosquitto-tls.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/mosquitto/passwd:/mosquitto/config/passwd
      - ./ssl/mqtt:/mosquitto/certs:ro
      - ${VOLUME_DATA}/mosquitto/data:/mosquitto/data
      - ${VOLUME_DATA}/mosquitto/log:/mosquitto/log
    logging:
      driver: json-file
      options:
        max-size: 50m

volumes:
  supla-server-socket: {}
