auth_plugin /mosquitto/go-auth.so
auth_opt_backends files, mysql

auth_opt_disable_superuser true

auth_opt_hasher pbkdf2
auth_opt_hasher_algorithm sha256
auth_opt_hasher_keylen 32

auth_opt_files_register user,acl
auth_opt_files_password_path /mosquitto/auth/passwords
auth_opt_files_acl_path /mosquitto/auth/acl

auth_opt_mysql_register user,acl
auth_opt_mysql_host __DB_HOST__
auth_opt_mysql_port __DB_PORT__
auth_opt_mysql_dbname __DB_NAME__
auth_opt_mysql_user __DB_USER__
auth_opt_mysql_password __DB_PASSWORD__
auth_opt_mysql_allow_native_passwords true
auth_opt_mysql_connect_tries 30
auth_opt_mysql_userquery SELECT mqtt_broker_auth_password FROM supla_user WHERE short_unique_id = ? AND mqtt_broker_enabled = 1 AND mqtt_broker_auth_password IS NOT NULL LIMIT 1
auth_opt_mysql_aclquery SELECT acl.topic FROM (SELECT 'supla/%u/#' AS topic, '1,3,4' AS access_modes UNION ALL SELECT 'homeassistant/+/%u/#' AS topic, '1,3,4' AS access_modes UNION ALL SELECT 'supla/%u/refresh_request' AS topic, '2,3' AS access_modes UNION ALL SELECT 'supla/%u/devices/+/channels/+/set/+' AS topic, '2,3' AS access_modes UNION ALL SELECT 'supla/%u/devices/+/channels/+/execute_action' AS topic, '2,3' AS access_modes) acl JOIN supla_user su ON su.short_unique_id = ? AND su.mqtt_broker_enabled = 1 WHERE FIND_IN_SET(CAST(? AS CHAR), acl.access_modes) > 0

auth_opt_cache true
auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_auth_jitter_seconds 3
auth_opt_acl_jitter_seconds 3

auth_opt_log_level info
auth_opt_log_dest stdout
