persistence true
persistence_location /mosquitto/data/

listener 1883 0.0.0.0
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/passwd

autosave_interval 180
connection_messages true
log_dest stdout
