auth_plugin /mosquitto/go-auth.so
auth_opt_backends http

auth_opt_http_host mqtt-auth
auth_opt_http_port 8080
auth_opt_http_getuser_uri /auth/user
auth_opt_http_superuser_uri /auth/superuser
auth_opt_http_aclcheck_uri /auth/acl
auth_opt_http_response_mode json
auth_opt_http_params_mode json
auth_opt_http_method POST
auth_opt_http_timeout 5
auth_opt_http_register user,superuser,acl

auth_opt_cache true
auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_auth_jitter_seconds 3
auth_opt_acl_jitter_seconds 3

auth_opt_log_level info
auth_opt_log_dest stdout
